project:
  type: book
  output-dir: docs

book:
  title: "CORN3000-EI"
  author: "Michael Hunt"
  date: "9/28/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  license: "CC BY-SA"
  page-footer: CC-BY-SA-4.0 (2025) Michael Hunt

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

execute:
  warning: false
  message: false

